--ADD_MONTHS
SELECT ADD_MONTHS(SYSDATE,
                  3) FROM DUAL;

SELECT ADD_MONTHS(DATE '2022-04-16',3) FROM DUAL;
SELECT ADD_MONTHS(DATE '2022-04-16',-3) FROM DUAL;

--CURRENT_DATE
SELECT CURRENT_DATE FROM DUAL;
SELECT SESSIONTIMEZONE FROM DUAL;

--TIMESTAMP
SELECT CURRENT_TIMESTAMP FROM DUAL;
SELECT CURRENT_TIMESTAMP,CURRENT_DATE FROM DUAL;

--SYSDATE
SELECT SYSDATE FROM DUAL;
SELECT SYSDATE -22/24 FROM DUAL;

--LAST_DAY
SELECT LAST_DAY(DATE '2022-02-05') FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT LAST_DAY(SYSDATE) - SYSDATE FROM DUAL;
SELECT LAST_DAY(ADD_MONTHS(SYSDATE,1)) FROM DUAL;

--NEXT_DAY
SELECT NEXT_DAY(SYSDATE,'THUERSDAY') FROM DUAL;
--MOUNTHS_BETWEEN
SELECT MONTHS_BETWEEN(DATE '2022-04-04',
                      DATE '2021-08-08') FROM DUAL;
--TRUNC
SELECT TRUNC(SYSDATE) FROM DUAL;
SELECT TRUNC(DATE '2022-10-10','DD') FROM DUAL;
SELECT TRUNC(DATE '2022-10-10','DAY') FROM DUAL;
SELECT TRUNC(DATE '2022-10-10','MONTH') FROM DUAL;
SELECT TRUNC(DATE '2022-10-10','Q') FROM DUAL;
SELECT TRUNC(DATE '2022-10-10','Y') FROM DUAL;

--ROUND
SELECT ROUND(TO_DATE('10.10.2008'),'MONTH') FROM DUAL;

--EXTRACT
SELECT EXTRACT(YEAR FROM DATE '2022-10-10') FROM DUAL;
SELECT EXTRACT(MONTH FROM DATE '2022-10-10') FROM DUAL;
SELECT EXTRACT(DAY FROM DATE '2022-10-10') FROM DUAL;
SELECT EXTRACT(HOUR FROM SYSTIMESTAMP) FROM DUAL;
SELECT EXTRACT(MINUTE FROM SYSTIMESTAMP) FROM DUAL;
SELECT EXTRACT(SECOND FROM SYSTIMESTAMP) FROM DUAL;

--TO_CAHR
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DL') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DL') AS ENGLISH, TO_CHAR(SYSDATE,'DL','NLS_DATE_LANGUAGE=FRENCH') AS FRENCH FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DAY') AS ENGLISH, TO_CHAR(SYSDATE,'DAY','NLS_DATE_LANGUAGE=FRENCH') AS FRENCH FROM DUAL;
SELECT TO_CHAR(INTERVAL '650' MINUTE,'HH24:MI') AS MINUTE FROM DUAL;
SELECT TO_CHAR(INTERVAL '650' HOUR,'HH24:MI') AS MINUTE FROM DUAL;


--TO_DATE
SELECT TO_DATE('21-12-2022','dd/mm/yyyy') as DATE_FORMAT FROM DUAL;
SELECT TO_DATE('21-12-2022','dd/mm/yyyy') - TO_DATE('21-12-2020','dd/mm/yyyy') AS Difference_Jour FROM DUAL;
SELECT TRUNC((TO_DATE('21-10-2025','dd/mm/yyyy') - TO_DATE('21-12-2020','dd/mm/yyyy'))/365) AS NOMBRE_ANNEE FROM DUAL;
SELECT TO_DATE('21-07-2021 05:46:31','dd-mm-yyyy hh24:mi:ss') AS HORA FROM DUAL;
