--index normal
CREATE INDEX ind_email_ville_clt
ON
clients(email,ville);

--index UNIQUE
CREATE UNIQUE INDEX ind_nom_prenom_clt
ON
clients(nom,prenom);

--table organisee en index
CREATE TABLE fournisseurs(
    codefrs NUMBER PRIMARY KEY,
    nom VARCHAR2(25) NOT NULL,
    prenom VARCHAR2(25) NOT NULL,
    tel VARCHAR2(14) UNIQUE,
    ville VARCHAR2(30)
)
ORGANIZATION INDEX;

--visualiser INDEX
SELECT INDEX_NAME ,TABLE_NAME,COLUMN_NAME,
COLUMN_POSITION
FROM USER_IND_COLUMNS
WHERE TABLE_NAME=UPPER('clients');

--cacher ou afficher INDEX
SELECT INDEX_NAME,VISIBILITY FROM USER_INDEXES
WHERE TABLE_NAME=UPPER('clients');
ALTER INDEX IND_EMAIL_VILLE_CLT INVISIBLE;

--modifier INDEX
ALTER INDEX IND_EMAIL_VILLE_CLT REBUILD;
--renommer INDEX
ALTER INDEX IND_EMAIL_VILLE_CLT RENAME TO  UX_IND_EMAIL_VILLE_CLT;
--suppression INDEX
SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME=UPPER('clients');
DROP INDEX UX_IND_EMAIL_VILLE_CLT;
DROP INDEX SYS_C007549;--cannot delete because have contraint
