--sequence
CREATE SEQUENCE seq_categorie
START WITH 1000
INCREMENT BY 10;

CREATE SEQUENCE seq_auteurs
START WITH 1000
INCREMENT BY 10;

CREATE SEQUENCE seq_membres
START WITH 1000
INCREMENT BY 10;

CREATE SEQUENCE seq_ouvrages
START WITH 1000
INCREMENT BY 10;


CREATE SEQUENCE seq_emprunts
START WITH 1000
INCREMENT BY 10;